# Generated by Django 5.2.7 on 2026-03-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='analysis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='score',
            name='down_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='filler_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='filler_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='left_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='long_pauses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='score',
            name='pause_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='raw_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='score',
            name='right_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='tempo_wpm',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='total_words',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='transcript',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='score',
            name='up_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='eye_contact_percentage',
            field=models.FloatField(default=0),
        ),
    ]
